### PR TITLE
Changes to support keyboard navigation

### LINKED ISSUE #1: Keyboard Navigation
Hey, it's Nolan from TR! Hope you've been doing well!
  
We've been asked to add keyboard navigation to our nav to meet some a11y requirements coming up in UK. I'd like to keep using navmore for now, so our package consumers there can get the keyboard navigation without making changes on their end.
  
I was thinking I'd do some work on it this week and then make a pull request here. Please let me know if you have any input!

### PR DESCRIPTION
**Pull request by njrey**
Fixes #1  
  
This update should provide keyboard navigation and require no additional changes for consumers

### CODE REVIEW

**Comment by pinkhominid** [comment]
Nolan, the code looks good and seems to work well. I have a couple concerns about the approach I want to share.

Are we compromising accessibility by diverging from natural depth-first, list tab order. Some might argue that for large deep lists (like Onvio's) breadth-first might be more user-friendly, but how does this affect the experience for users with screen readers?

Also, if a consumer is setting a tabindex on any of the slotted elements we are overriding their wishes.

**Comment by njrey** [comment]
Thanks for the feedback John, I had some of the same concerns.
  
I actually confirmed with analysts and our UX team that the breadth-first search behavior is what they want since it requires less tabbing for keyboard navigation users.
  
For users with screen readers, I'm wondering if consuming apps could add something to their h1's to indicate when it has nested nav-items. I know some dropdown menus use `aria-haspopup` to indicate sublevel menu items on an element.
  
For the tabindex issue, I believe we're okay since this is the tab behavior UI/UX would like to see consistently across all nav menus. Let me know what you think though. I wouldn't want to break anyone's menus, but I haven't come across any tabindexed navmore menus in Onvio so far.

**Comment by pinkhominid** [comment]
The line between nav lists and menus/popups is definitely blurry and I can def understand the need for breadth-first traversal when you have a heavy second or third level.

The tabindex concern was more for other pkg consumers sake. Of course Onvio might be the only, lol. Hard to tell from npm download stats.

I'm good with merging your PR. Thanks for the PR and helping to think through this 👍

**Comment by njrey** [comment]
Thank you! I appreciate your input, and it was nice working through this one like the old days! Will this change require a new version so we can consume it via npm?

**Comment by pinkhominid** [comment]
Yep, I will cut a new major version.

**Pull request merged**
